version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --ISCAgent false
    restart: always
    ports: 
      - 51972:1972
      - 53795:52773
      - 53773
      - 8051:8051
    volumes:
      - ./:/irisdev/app
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
